//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTapChuyenMon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChucVu()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int IdChucVu { get; set; }
        public string TenChucVu { get; set; }
        public Nullable<int> LuongCoBan { get; set; }
        public Nullable<bool> BanHang { get; set; }
        public Nullable<bool> PhaChe { get; set; }
        public Nullable<bool> ThongKe { get; set; }
        public Nullable<bool> QuanLy { get; set; }
        public Nullable<bool> HeThong { get; set; }
        public Nullable<bool> Kho { get; set; }
        public Nullable<bool> KhachHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
