//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTapChuyenMon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHoaDon
    {
        public int IdHoaDon { get; set; }
        public int IdDoUong { get; set; }
        public string Size { get; set; }
        public string SoLuong { get; set; }
    
        public virtual CTDoUong CTDoUong { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
