//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTapChuyenMon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuXuat
    {
        public int IdPhieuXuat { get; set; }
        public int IdNguyenLieu { get; set; }
        public Nullable<double> SoLuong { get; set; }
    
        public virtual PhieuXuat PhieuXuat { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
