//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTapChuyenMon
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string IdKhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> IdLoai { get; set; }
        public Nullable<int> DiemTichLuy { get; set; }
        public Nullable<System.DateTime> NgayLapThe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual LoaiKhachHang LoaiKhachHang { get; set; }
    }
}
